### ISSUE TITLE
Remove nux=1

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#10]

**Comment by Cyberdada** [comment]
Or at leas explain somewhere why it is included.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
