### ISSUE TITLE
Enable Cors Attribute

### ISSUE THREAD

**Issue by jasteph** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#11]
In Step 3 - Instruction 5 we are told "In the [EnableCors...] attribute, enter the location of the To Do SPA client."
1. I don't see any EnableCors attribute in the controller.
2. I don't see EnableCors attribute in any of the referenced libraries.

If I add a reference to Microsoft.AspNet.WebApi.Cors then I get the attribute, but this doesn't seem right to me.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
