### ISSUE TITLE
Unhandled error in oauth authorize call made for CORS request

### ISSUE THREAD

**Issue by erchinoald** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#13]
The example worked at first but for the last two days I have been getting this error with the call to AAD which is made to get the auth token for CORS request to the ToGoAPI:
"AADSTS90033: Service is temporarily unavailable. Please retry later"

Although this appears to be a server-side issue with AAD, the response code is 200 and it doesn't seem to be triggering the authentication failed event. I think this type of response should trigger the authentication failed event so that it can be handled by the application.

Also, I wanted to share here to see if maybe it's related to compatibility between the example code or adal-js library and the azure AD service. Azure status page reports no problem with Azure AD and the error seems to be confined to this specific scenario. I also have a support ticket open with Azure AD so I will post back here if they find anything on their end.

**Comment by tgschulte** [comment]
I imagine this is on the Azure side, but I just saw this error 2016-04-29 10:45:50Z which was the first time for me. Other calls to my AAD instance for tokens immediately before and after succeeded.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
