### ISSUE TITLE
EnableCors attribute missing

### ISSUE THREAD

**Issue by leechen** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#18]
Following this direction: 5. Also in the ToGoAPI project, open the file Controllers/ToGoListController.cs. In the [EnableCors...] attribute, enter the location of the To Do SPA client. By default it is https://localhost:44326. Make sure to omit the trailing slash.

There is actually no EnableCors attribute in ToGoListController.cs

**Comment by isaac2004** [comment]
To add, the nuget package is not even in there, you have to add it

Install-Package Microsoft.AspNet.WebApi.Cors

**Comment by alexakarpov** [comment]
I wonder if this is actually tracked, given the lack of the responses..

**Comment by michaelsync** [comment]
I think you can ignore this step. I was able to call the ToGoList.

**Comment by michaelsync** [comment]
same issue as this https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/11

**Comment by nealYangVic** [comment]
It doesn't need, because int Startup.cs TO go api, there is app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

Allow ALL

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
