### ISSUE TITLE
In local vS it is authenticating the User , when deploying to azure it is not

### ISSUE THREAD

**Issue by shilsmarty** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#2]
In local VS it is authenticating the User and in webApi able to get the claims for the loggedInuser , when deploying it to Azure environment (Web on cloudservice and Service on WebSites) it is not authenticating the user and throwing the user "Authentication has been denied for this user".

**Comment by vibronet** [comment]
if the client and the web API are on different URLs, the basic logon won't work. See https://github.com/AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet for an example in which a SPA invokes a service on a different origin

**Comment by shilsmarty** [comment]
Thank you ,for quick response ,
I followed the AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet sample , integrating with my actual solution on local VS it worked fine but on deployment to azure it is not sending the token to webApi service.

also I am using adal.js v 0.0.1 not 1.0.0 do you think it can be problem ?

**Comment by JayChase** [comment]
Hi. I'm not sure if anyone is still watching this issue but if so could you clarify whether this scenario of having different origins the SPA and API can be made to work?

**Comment by shailensukul** [comment]
Possibly related to this issue: https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/12 ?

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
