### ISSUE TITLE
Code for Angular2

### ISSUE THREAD

**Issue by garybushey** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#20]
Not really an issue but are there plans to update this for Angular2?

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
