### ISSUE TITLE
401 - Unauthorized, am i missing something?

### ISSUE THREAD

**Issue by JohnMarcus89** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#21]
Ok so i know this issue has been up 2 or more times already but i really don't know what i'm doing wrong here...

I've been following the [Azure Active Directory developer's guide](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-developers-guide) as closely as i can... Specifically these parts:

 [Securing AngularJS Single Page Apps with Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-devquickstarts-angular)

[Call an Azure AD protected Web API in an AngularJS Single Page App](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi)

[Protect a Web API using Bearer tokens from Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-devquickstarts-webapi-dotnet)

I have redone the "dummy-project" 4 times exactly and get the same resaults....

Is this a full step by step guide or is something missing that you guys think should already be known.
What am i missing?

**Comment by michaelsync** [comment]
For me, calling the ToGoList is working .. 

But not the ToDoList. [Ref](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/29)

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
