### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by nilMicro** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#22]
I have follow this steps more than 4 5 times from scratch as well as configure the existing code 2 times but it shows the 401 Unauthorized url.

Any one know how this would be resolve. 

Thanks,
Nilesh

**Comment by siva524** [comment]
I am also facing same issue.Any Solution for this.

**Comment by cnuis2cool** [comment]
I had the same problem. In endpoints I had put APP URI ID, replaced it with App ID.

var endpoints = {

        // Map the location of a request to an API to a the identifier of the associated resource
        "https://localhost:44327/": "<Application ID>" // Not APP URI ID
     };

Also enabled CORS for Web API.
Followed this: https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api

**Comment by michaelsync** [comment]
For me, putting App URI works. 

but I got [two other issues](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/29).

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
