### ISSUE TITLE
ToGoListServiceContext.mdf missing from source code files?

### ISSUE THREAD

**Issue by lizetpena** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#23]
Hi,
Where could I find the database files used on this project?

Thanks in advance,
-Lizet

**Comment by michaelsync** [comment]
Yes. I got this error as well. but I only want to see how ADAL JS works so I deleted all database stuffs and replaced with a `List<ToGo>`

**Comment by lizetpena** [comment]
I also changed the use of the database and EF by an in-memory list. The sample code is meant to illustrate the OAuth2.0 Implicit flow and the integration with AAD, so the DAL used, is not really relevant in the solution.

**Comment by notoriousedd** [comment]
Hi Guys... can you share how you changed the web.config to use a list instead of the SQL DB connection?  I am not a developer so I'm struggling to figure that out.  I am an identity/infrastructure guy. :)

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
