### ISSUE TITLE
Continuosuly Refreshing Redirected Url.

### ISSUE THREAD

**Issue by siva524** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#24]
HI,
     I downloaded your code.it was very nice example i saw on authentication.I am getting continuously loading redirecting url .can you tell me to resolve this issue.

Thanks.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
