### ISSUE TITLE
Can we have a javascript app without asp.net project in this sample? 

### ISSUE THREAD

**Issue by michaelsync** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#27]
Hello,

I am wondering why the javascript app is being put in asp.net project. 

Example: 
https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/tree/master/TodoSPA

Would it be better if the SPA has only javascript project that talks with API? 

Regards,
MS

**Comment by jmprieur** [comment]
Would this example help you?
https://github.com/microsoftgraph/angular-connect-rest-sample
