### ISSUE TITLE
Typo in Step 3 - 5?

### ISSUE THREAD

**Issue by michaelsync** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#28]
Hi,

The following was mentioned in Step 3 no 5,

> Also in the ToGoAPI project, open the file Controllers/ToGoListController.cs. In the [EnableCors...] attribute, enter the location of the To Do SPA client. By default it is https://localhost:44326. Make sure to omit the trailing slash.

But there are no EnableCors attribute in `Controllers/ToGoListController.cs` or the whole project. 

Please check here https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/blob/master/ToGoAPI/Controllers/ToGoListController.cs 

Am I missing something or was it the typo in the guide? 

Thanks.

**Comment by seed-of-apricot** [comment]
#18 
There's the same issue already open.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
