### ISSUE TITLE
Two issues in sample

### ISSUE THREAD

**Issue by michaelsync** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#29]
Hi,

Thanks for providing this example. I've been playing around and found two issues.  Feel free to let me know if I miss out something. 

1.  "Authorization has been denied for this request." for "To Do List" 

ToDoList controller is in SPA project but I got this error above after login. 

Steps to replicate ~ 
 - Run the project 
 - Open this link https://localhost:44326 in Chrome private mode
 - Click on 'To Do List' (It will ask you to log in. I logged in with my account )
 - It shows "Authorization has been denied for this request." in ToDoList page after successfuly logged in. 
 - Check the Login/Logout text on the header (You will see the "Log out" - so it means the login was a success as well.)

2. 'Login/In' text

 - Follow the step above.
 - Click on 'To Go List'
 - Observe the Login/Logout text on the header - (**Error**: It changed it to 'Login' again. )
 - **ERROR**: You will get the "Authorization has been denied for this request." in 'To Go List' as well. 
 - Click back on "To Do List" again.  (same auth error)
 - Click again on "To Go List" - (There, you will see the list.  and the text on the header is still 'Login'. )

![image](https://user-images.githubusercontent.com/192911/33590628-ce7668d8-d9d4-11e7-9a51-dc92cb7adee6.png)

Note: Please ignore the data. As I mentioned [here](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi/issues/23#issuecomment-349194101), I replaced the DAL with a List. 

Thanks. Feel free to let me know if you need more information or if I miss out something.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
