### ISSUE TITLE
i am getting following message while clicking login

### ISSUE THREAD

**Issue by rakshiraik** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#30]
Request Id: f106b5ad-6392-4c41-8fa2-473629870700
Correlation Id: 6abe676b-e3d0-41e2-8255-829dff79b6b0
Timestamp: 2018-04-12T07:52:15Z
Message: AADSTS65005: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 8f4b3482-68c1-42b1-b4dd-ea1e0ad9a65e. Resource value from request: . Resource app ID: 00000002-0000-0000-c000-000000000000. List of valid resources from app registration: c7aee132-6d62-4d80-9511-057c9420fd2b.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
