### ISSUE TITLE
AADSTS90008: This happened because application is misconfigured

### ISSUE THREAD

**Issue by MrJunaidShahid** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#31]
Am getting the error while trying to integrate Azure Active Directory Login in WPF application,

AADSTS90008: The user or administrator has not consented to use the application with ID 'ApplicationID' (ApplicationName). This happened because application is misconfigured: it must require access to Microsoft Graph by specifying at least **'Sign in and read user profile'** permission.

**Comment by derisen** [comment]
It looks like your application is not configured properly to request the necessary [consent scopes](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent). More than this is hard to tell without seeing your configuration. You mention WPF -is the issue related to this sample?

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
