### ISSUE TITLE
getting no access control error

### ISSUE THREAD

**Issue by bigerock** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#4]
i'm getting a 'no access control allow origin' error (see below) when i've updated this project to use iis instead of iis express using local host headers. meaning, i've switched from using https://localhost:[port] to something like http://myapi.test for my web api and http://myapp.test for my app in iis. i've added the 'EnableCors' attribute on my web api controller, and properly called out http://myapp.test within the attributes - as the example has shown.

does this perhaps need a fully qualified domain in order to run properly?

Error:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://myapp.test' is therefore not allowed access. The response had HTTP status code 405.

on my controller:
[EnableCors("http://myapp.test", "_", "_")]

**Comment by omercs** [comment]
Fully qualified domain name issue is related to the IE browser. 
Error is saying that server side is not sending the  'Access-Control-Allow-Origin' header. Browsers check that header for CORS request.

**Comment by bigerock** [comment]
do you have any idea what I might try then?

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
