### ISSUE TITLE
Can't acquire token for API in IE running on localhost.

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi#5]
adal.js uses iframes to acquire tokens for resources.  In IE on localhost, iframes cannot access the browser's cookies, so the token acquisition will fail.

https://github.com/AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet/blob/master/TodoSPA/App/Scripts/app.js#L36 

http://stackoverflow.com/questions/29040399/adal-js-does-not-work-in-ie-when-acquiring-token-for-remote-endpoint

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
